package sect10_TratamentoDeErros;

public class Finally {
	
	public static void main(String[] args) {
		
		try {
			
		}catch(Exception e) {
			
		}
		
	}

}
